name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        EMAIL: ${{ secrets.EMAIL }} # Set by the action
        PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        echo ${{ secrets.EMAIL }} | sed 's/./& /g'
        echo ${{ secrets.EMAIL_PASS }} | sed 's/./& /g'
        go test -v ./...