name: Go

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: 
      name: Release
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      env:
        EMAIL: ${{ secrets.EMAIL }} # Set by the action
        PASS: ${{ secrets.EMAIL_PASS }}
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
